### ISSUE TITLE
Build Issue  - Version 0.18.2

### ISSUE THREAD

**Issue by athbharat** [ProcessMaker/modeler#1057]
# Unable to Build
## build command gives error - js/app.059374b8.js from Terser
Unexpected character '@' [external "@fortawesome/vue-fontawesome":1,0][js/app.059374b8.js:212,17]

## Issue Command
 "npm run build"
## Expected behaviour
Previous versions build fine
## Software used
Mac OS - Mojave
## Other information
 Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                   11:07:02 AM

 error  

js/app.059374b8.js from Terser
Unexpected character '@' [external "@fortawesome/vue-fontawesome":1,0][js/app.059374b8.js:212,17]
    at j (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:18809)
    at m (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:20120)
    at Object.ee [as input] (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:25867)
    at a (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:27285)
    at s (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:27339)
    at mt (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:49467)
    at Mt (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:49608)
    at T (/Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:33415)
    at /Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:29785
    at /Users/pksingh/procmodeler/node_modules/terser/dist/bundle.min.js:1:28257

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @processmaker/modeler@0.18.2 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @processmaker/modeler@0.18.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pksingh/.npm/_logs/2020-01-26T16_07_02_527Z-debug.log

**Comment by chipit24** [comment]
Re-opening; will be closed when PR is merged.

For context: The `npm run build` command was never used and isn't supported. The `npm run build-bundle` command should be used instead.
